Repository MicrosoftDocs/microsoft-365-community, pull requests merged in 2024-06, with the labels that each got.

#950 Publish main to live, Thursday 10:30AM PDT, 06/06
  Community/TOC.md
  Community/TOC.yml
Labels: Microsoft submitter

#952 Publish main to live, Monday 3:30PM PDT, 06/17
  CHANGELOG.md
  Community/microsoft365-maturity-model--management-of-content.md
Labels: Microsoft submitter, microsoft-365/svc

#953 Updates to Team Site vs. Communication Site: Which one should I choose?
  Community/team-site-or-communication-site.md
Labels: sharepoint-online/svc, In review, Sign off

#954 Minor Acrolinx and formatting fixes
  Community/team-site-or-communication-site.md
Labels: Microsoft submitter, sharepoint-online/svc

#955 Publish main to live 06/24/2024, 3:30 PM
  Community/team-site-or-communication-site.md
Labels: Microsoft submitter, sharepoint-online/svc

#958 Publish main to live, Friday 10:30AM PDT, 06/28
  Community/machine-learning-and-managed-metadata.md
Labels: Microsoft submitter, sharepoint-online/svc
