Repository MicrosoftDocs/microsoft-365-community, pull requests merged in 2024-02, with the labels that each got.

#892 merge main to live 3:30 PM 1/31/24
  .vscode/settings.json
  CHANGELOG.md
  Community/media/microsoft365-maturity-model-cognitive-business/ai-spectrum.png
  Community/media/microsoft365-maturity-model-cognitive-business/ai-value.jpg
  Community/media/microsoft365-maturity-model-cognitive-business/autopilot-to-copilot.png
  Community/media/microsoft365-maturity-model-cognitive-business/evolution.png
  Community/microsoft365-maturity-model--cognitive-business.md
Labels: Microsoft submitter, microsoft-365/svc

#901 Update power-automate-vs-logic-apps.md
  Community/power-automate-vs-logic-apps.md
Labels: article issue, In review, Sign off, power-platform/svc

#902 Updated CHANGELOG
  CHANGELOG.md
Labels: doc-enhancement, In review, Sign off

#903 Publish main to live, Wednesday 10:30AM PST, 02/14
  CHANGELOG.md
  Community/power-automate-vs-logic-apps.md
Labels: Microsoft submitter, power-platform/svc

#906 Updates to CHANGELOG
  CHANGELOG.md
Labels: In review, Sign off

#904 Update which-task-management-option.md with latest Loop updates
  Community/which-task-management-option.md
Labels: microsoft-365/svc, In review, Sign off

#905 Fixed typo - principle
  Community/creating-useful-views-in-lists-libraries.md
Labels: sharepoint-online/svc, In review, Sign off

#907 Publish main to live, Tuesday 10:30AM PST, 02/20
  CHANGELOG.md
  Community/creating-useful-views-in-lists-libraries.md
  Community/which-task-management-option.md
Labels: Microsoft submitter, microsoft-365/svc, sharepoint-online/svc

#908 Publish main to live, Monday 10:30AM PST, 02/26
  Community/includes/community-content-updates.md
Labels: Microsoft submitter

#910 Updating People and Communities to include new thoughts and ideas for 2024. Includes thoughts on staff retention
  Community/microsoft365-maturity-model--people-and-communities-competency.md
Labels: microsoft-365/svc, In review, Sign off

#911 Updates to CHANGELOG
  CHANGELOG.md
Labels: In review, Sign off
