Repository MicrosoftDocs/microsoft-365-community, pull requests merged in 2025-04, with the labels that each got.

#1053 Update versioning-basics-best-practices.md
  Community/versioning-basics-best-practices.md
Labels: sharepoint-online/svc, In review, Sign off

#1055 Publish main to live, 04/01/25, 10:30 AM PDT
  Community/versioning-basics-best-practices.md
Labels: Microsoft submitter, sharepoint-online/svc

#1057 Publish main to live, 04/08/25, 10:30 AM PDT
  Community/principles-of-communication.md
Labels: Microsoft submitter, microsoft-365/svc

#1059 Merge AutoPublish workflow to live
  .github/workflows/AutoPublish.yml
Labels: Microsoft submitter

#1061 Fixed broken links in issue #1060
  Community/glossary.md
  Community/government-cloud.md
  Community/how-can-i-use-learning-pathways-in-my-organization.md
  Community/media/library-scenarios/index.md
  Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md
  Community/type-of-apps-microsoft-365.md
Labels: microsoft-365/svc, o365-solutions/svc, sharepoint-online/svc, In review, Sign off, msteams/svc, PubOps fixes

#1063 Update links and text in ThirdPartyNotices.md per CELA request
  ThirdPartyNotices.md
Labels: Microsoft submitter

#1066 StaleBranch reporting updates and cron changes to live
  .github/workflows/StaleBranch.yml
Labels: Microsoft submitter

#1067 Reorganized TOC and index for MM4M365
  Community/TOC.yml
  Community/index-mm4m365.yml
Labels: sharepoint-online/svc, In review, Sign off
